teste = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(teste))
print('Só tem espaços: ', teste.isspace())
print('É alfanumérico: ', teste.isalnum())
print('É alfabético: ', teste.isalpha())
print('É numérico: ', teste.isnumeric())
print('Está em maiúsculas: ', teste.isupper())
print('Está em minúsculas: ', teste.islower())
print('Está capitalizada: ', teste.istitle())
